"""
make_readme.py
==============

Generates results/README.md: a map from every figure filename to its
(section, dataset, method, variant), plus the logged hyperparameters / seeds
(§0.5 reproducibility) and a short guide to results_indices.csv.

Run after the three §5 drivers so every figure is on disk.
"""

from __future__ import annotations

from src import indices as ix
from src.section5_common import (
    DIFFUSION_T,
    K_NEIGHBORS,
    LR_RV,
    N_ITER_RV,
    PERPLEXITY,
    RESULTS_DIR,
    SECTION_FLOOR_RUNS,
    SEED,
    TRUST_K,
    Q,
)

SECTION_TITLES = {
    "5.3.1": "Spectral methods — exact recovery",
    "5.3.2": "Approximations — geometric (stochastic floor)",
    "5.3.3": "Hybrid methods — novelty / flexibility",
}
VARIANT_DESC = {
    "overlay": "Procrustes overlay / side-by-side scatter (framework vs reference)",
    "qnx": "Q_NX(k) curve: framework vs reference vs stochastic-floor band",
    "control": "UMAP init negative control (reference PCA-init vs random-init)",
    "grid": "α×ν grid / α-sweep of embeddings",
    "quality": "quality-vs-sweep curves (trustworthiness / ARI)",
}
DATASET_DESC = {
    "singlecell": "10x PBMC3k (scanpy-processed, PCA→50, cell-type labels)",
    "mnist": "MNIST 2000 balanced (PCA→50, digit labels)",
    "swissroll": "Swiss-roll 2000 (raw 3D, continuous roll angle)",
}


def parse(fname: str) -> tuple[str, str, str, str] | None:
    stem = fname[:-4] if fname.endswith(".png") else fname
    if not stem.startswith("fig_"):
        return None
    parts = stem[len("fig_") :].split("_")
    if len(parts) < 4:
        return None
    section, dataset, *mid, variant = parts
    method = "_".join(mid)
    return section, dataset, method, variant


def main() -> None:
    fig_dir = RESULTS_DIR / "figures"
    figs = sorted(p.name for p in fig_dir.glob("*.png"))
    rows = [(f, parse(f)) for f in figs]
    rows = [(f, p) for f, p in rows if p is not None]

    lines: list[str] = []
    lines.append("# §5 Case Studies — results map\n")
    lines.append(
        "Generated by `scripts/make_readme.py`. Every figure follows the §0.5 "
        "convention `fig_{section}_{dataset}_{method}_{variant}.png`; all scalar "
        "indices live in `results_indices.csv`.\n"
    )

    # ── reproducibility ──
    lines.append("## Hyperparameters & seeds (§0.5)\n")
    lines.append(f"- `random_state` / SEED = **{SEED}** (everywhere)")
    lines.append(f"- embedding dim q = **{Q}**")
    lines.append(f"- kNN neighbours (graph methods / UMAP) k = **{K_NEIGHBORS}**")
    lines.append(f"- t-SNE perplexity / adaptive-Gaussian = **{PERPLEXITY}**")
    lines.append(f"- diffusion time t = **{DIFFUSION_T}**")
    lines.append(f"- RV gradient ascent: **{N_ITER_RV}** iters, Adam lr = **{LR_RV}**")
    lines.append(
        f"- index neighbourhood k (trustworthiness / kNN overlap) = **{TRUST_K}**"
    )
    lines.append(f"- Q_NX(k) grid = {ix.QNX_KS}")
    lines.append(f"- stochastic-floor reference runs = **{SECTION_FLOOR_RUNS}**")
    lines.append(
        "- init: framework uses full-scale PCA; sklearn t-SNE / UMAP references use "
        "the PCA init scaled to PC1 std 1e-4 (§0.2). Both share PCA directions, so "
        "Procrustes/RV comparisons stay legitimate.\n"
    )

    # ── datasets ──
    lines.append("## Datasets (§0.1)\n")
    for k, v in DATASET_DESC.items():
        lines.append(f"- **{k}** — {v}")
    lines.append("")

    # ── figure map, grouped by section then dataset ──
    lines.append("## Figure map\n")
    for section in sorted({p[0] for _, p in rows}):
        lines.append(f"### §{section} — {SECTION_TITLES.get(section, '')}\n")
        lines.append("| file | dataset | method | variant | description |")
        lines.append("|---|---|---|---|---|")
        for fname, (sec, dataset, method, variant) in rows:
            if sec != section:
                continue
            desc = VARIANT_DESC.get(variant, "")
            lines.append(f"| `{fname}` | {dataset} | {method} | {variant} | {desc} |")
        lines.append("")

    # ── CSV guide ──
    lines.append("## results_indices.csv\n")
    lines.append(
        "Tidy long format, one row per index value. Columns: "
        "`section, dataset, method, variant, init, index_name, k, value, run_id`.\n"
    )
    lines.append("Key `index_name` values:")
    lines.append("- `procrustes`, `knn_overlap` — identity (framework vs reference)")
    lines.append(
        "- `*_floor_mean`, `*_floor_std` — stochastic floor over reference runs"
    )
    lines.append("- `trustworthiness`, `q_local`, `ari` — quality")
    lines.append("- `rv_final` — final RV coefficient of the framework optimisation\n")

    out = RESULTS_DIR / "README.md"
    out.write_text("\n".join(lines))
    print(f"Wrote {out}  ({len(rows)} figures mapped)")


if __name__ == "__main__":
    main()
