"""
make_readme.py
==============

Generates results/README.md: a map from every figure filename to its
(section, dataset, method, variant), plus the logged hyperparameters / seeds
(§0.5 reproducibility) and a short guide to results_indices.csv.

Run after the three §5 drivers so every figure is on disk.
"""

from __future__ import annotations

from src.section5_common import (
    DIFFUSION_T,
    K_NEIGHBORS,
    LR_RV,
    N_ITER_RV,
    PERPLEXITY,
    RESULTS_DIR,
    SEED,
    TRUST_K,
    Q,
)

SECTION_TITLES = {
    "5.3.1": "Spectral methods — exact recovery",
    "5.3.2": "Approximations — geometric (PCA-init reference)",
    "5.3.3": "Hybrid methods — novelty / flexibility",
}
VARIANT_DESC = {
    "linear": "framework w/ LINEAR output kernel (√λ-scaled axes)",
    "projector": "framework w/ PROJECTOR output kernel (balanced axes)",
    "framework": "framework embedding (RV-maximised), Procrustes-aligned to reference",
    "reference": "reference embedding (library implementation), standardised frame",
    "comparison": "output-kernel comparison: Procrustes & kNN overlap per method",
    "grid": "α×ν grid / α-sweep of embeddings",
    "quality": "quality-vs-sweep curves (trustworthiness / ARI)",
}
DATASET_DESC = {
    "singlecell": "10x PBMC3k (scanpy-processed, PCA→50, cell-type labels)",
    "mnist": "MNIST 2000 balanced (raw 784 pixels, digit labels)",
    "swissroll": "Swiss-roll 2000 (raw 3D, continuous roll angle)",
}


def parse(fname: str) -> tuple[str, str, str, str] | None:
    stem = fname[:-4] if fname.endswith(".png") else fname
    if not stem.startswith("fig_"):
        return None
    parts = stem[len("fig_") :].split("_")
    if len(parts) < 4:
        return None
    section, dataset, *mid, variant = parts
    method = "_".join(mid)
    return section, dataset, method, variant


def main() -> None:
    fig_dir = RESULTS_DIR / "figures"
    figs = sorted(p.name for p in fig_dir.glob("*.png"))
    rows = [(f, parse(f)) for f in figs]
    rows = [(f, p) for f, p in rows if p is not None]

    lines: list[str] = []
    lines.append("# §5 Case Studies — results map\n")
    lines.append(
        "Generated by `scripts/make_readme.py`. Every figure follows the §0.5 "
        "convention `fig_{section}_{dataset}_{method}_{variant}.png`; all scalar "
        "indices live in `results_indices.csv`.\n"
    )

    # ── reproducibility ──
    lines.append("## Hyperparameters & seeds (§0.5)\n")
    lines.append(f"- `random_state` / SEED = **{SEED}** (everywhere)")
    lines.append(f"- embedding dim q = **{Q}**")
    lines.append(f"- kNN neighbours (graph methods / UMAP) k = **{K_NEIGHBORS}**")
    lines.append(f"- t-SNE perplexity / adaptive-Gaussian = **{PERPLEXITY}**")
    lines.append(f"- diffusion time t = **{DIFFUSION_T}**")
    lines.append(f"- RV gradient ascent: **{N_ITER_RV}** iters, Adam lr = **{LR_RV}**")
    lines.append(
        f"- index neighbourhood k (trustworthiness / kNN overlap) = **{TRUST_K}**"
    )
    lines.append(
        "- init: framework uses full-scale PCA; sklearn t-SNE / UMAP references use "
        "the PCA init scaled to PC1 std 1e-4 (§0.2). Both share PCA directions, so "
        "Procrustes/RV comparisons stay legitimate.\n"
    )

    # ── datasets ──
    lines.append("## Datasets (§0.1)\n")
    for k, v in DATASET_DESC.items():
        lines.append(f"- **{k}** — {v}")
    lines.append("")

    # ── figure map, grouped by section then dataset ──
    lines.append("## Figure map\n")
    for section in sorted({p[0] for _, p in rows}):
        lines.append(f"### §{section} — {SECTION_TITLES.get(section, '')}\n")
        lines.append("| file | dataset | method | variant | description |")
        lines.append("|---|---|---|---|---|")
        for fname, (sec, dataset, method, variant) in rows:
            if sec != section:
                continue
            desc = VARIANT_DESC.get(variant, "")
            lines.append(f"| `{fname}` | {dataset} | {method} | {variant} | {desc} |")
        lines.append("")

    # ── saved coordinates ──
    lines.append("## Saved coordinates (§5.3.1)\n")
    lines.append(
        "`results/coordinates/spectral/{dataset}__{method}__{role}.npy` holds the raw "
        "(n×2) embeddings, role ∈ {`reference`, `framework_linear`, "
        "`framework_projector`}; `run_meta.csv` logs the final RV per run. "
        "`spectral_indices.py` and `spectral_figures.py` are built entirely from "
        "these files.\n"
    )

    # ── output-kernel choice ──
    lines.append("## Output kernels: linear vs projector (§5.3.1)\n")
    lines.append(
        "Each spectral method is run twice, with a LINEAR output kernel "
        "(`K_Y = ỸỸᵀ`, axis i scaled by √λ_i) and with the PROJECTOR output kernel "
        "(`K_Y = Ỹ(ỸᵀỸ)⁻¹Ỹᵀ`, the orthogonal projector onto span(Ỹ), all nonzero "
        "eigenvalues = 1). The projector is invariant to any reparametrisation "
        "`Y → Y M`, so RV depends only on the embedding *subspace* and the recovered "
        "axes are balanced by construction (no √λ anisotropy).\n"
    )
    lines.append("**Recommended use: projector for LLE and Laplacian Eigenmaps only; "
                 "linear for PCA, Kernel PCA, Isomap and Diffusion Maps.**\n")
    lines.append("Why this split:")
    lines.append(
        "- PCA / Kernel PCA / Isomap / Diffusion have a well-conditioned input "
        "spectrum: a clear gap *and* comparable top eigenvalues. The linear kernel "
        "recovers them almost exactly (Procrustes ≈ 0). The projector only adds a "
        "small gauge/orthonormalisation rotation, so linear is marginally better."
    )
    lines.append(
        "- LLE and Laplacian Eigenmaps are pseudo-inverses of a graph operator; their "
        "bottom spectrum is strongly imbalanced (λ₂ ≪ λ₃, e.g. λ₃/λ₂ ≈ 59 on "
        "single-cell LLE). Under the linear kernel the embedding axes inherit a "
        "√(λ₃/λ₂) anisotropy that Procrustes (one global scale, not per-axis) cannot "
        "absorb, while the reference eigenvectors are unit-norm/balanced. The "
        "projector removes this scaling degree of freedom and recovers the same "
        "subspace with balanced axes — hence the large gains (LLE single-cell "
        "0.384→0.066, mnist 0.028→0.000; Laplacian swissroll 0.108→0.003)."
    )
    lines.append(
        "- Decision rule = the ratio of the top-two input eigenvalues (effective "
        "spectral dimensionality): ≈1 → kernels agree, keep linear; ≫1 → use the "
        "projector.\n"
    )

    # ── LLE on swissroll ──
    lines.append("### Why LLE recovers poorly on swissroll\n")
    lines.append(
        "LLE stays high on swissroll under *both* output kernels (linear 0.489, "
        "projector 0.667). This is not a readout issue but intrinsic to LLE on a "
        "smooth manifold: the bottom of `Φ = (I−W)ᵀ(I−W)` is **near-degenerate** "
        "(several smallest eigenvalues almost equal), so the 2-D embedding subspace "
        "is not uniquely defined — the boundary-gap degeneracy `λ_q ≈ λ_{q+1}` that "
        "no output kernel can fix, since it is a property of the data + LLE, not of "
        "the readout. sklearn's eigensolver and the RV optimiser each pick a valid "
        "but different subspace from the degenerate bottom cluster, so their "
        "Procrustes is large even though both are legitimate LLE embeddings with "
        "near-identical RV. Isomap and diffusion, which have a clean spectral gap on "
        "the swiss roll, recover near-exactly. This is a documented weakness of LLE "
        "(regularisation sensitivity + eigenvalue crowding), not a framework bug.\n"
    )

    # ── CSV guide ──
    lines.append("## results_indices.csv\n")
    lines.append(
        "Tidy long format, one row per index value. Columns: "
        "`section, dataset, method, variant, init, index_name, k, value, run_id`.\n"
    )
    lines.append("Key `index_name` values:")
    lines.append("- `procrustes`, `knn_overlap` — identity (framework vs reference)")
    lines.append("- `trustworthiness`, `ari` — quality (per variant)")
    lines.append("- `rv_final` — final RV coefficient of the framework optimisation\n")

    out = RESULTS_DIR / "README.md"
    out.write_text("\n".join(lines))
    print(f"Wrote {out}  ({len(rows)} figures mapped)")


if __name__ == "__main__":
    main()
